version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - "database"
    networks:
      - "mynet"
    environment:
      PORT: 8000
      ENVIRONMENT: dev
      MYSQL_HOST: db-mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpw
      MYSQL_DATABASE: warehouse_development
  database:
    platform: "linux/x86_64"
    image: "mysql:5.7"
    container_name: "db-mysql"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "warehouse_development"
      MYSQL_ROOT_PASSWORD: "rootpw"
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - "mynet"
  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - database
    networks:
      - "mynet"
    volumes:
      - ./db/migrations:/db/migrations
    command:
      [ "-path", "/db/migrations/", "-database",  "mysql://root:rootpw@tcp(db-mysql:3306)/warehouse_development?multiStatements=true", "up" ]
networks:
  mynet:
    external: true
volumes:
  mysql-data:
